#!/bin/bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

script_dir() {
    cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
}

cursor_home() {
    if [ -n "${CURSOR_HOME:-}" ]; then
        printf '%s\n' "$CURSOR_HOME"
    else
        printf '%s\n' "${HOME}/.cursor"
    fi
}

generate_cursor_rules() {
    local rules_dir="$1"
    local rules_dest="$2"
    local agents_file="$3"
    local rules_found=0

    mkdir -p "$rules_dest"
    find "$rules_dest" -maxdepth 1 -type f -name '*.mdc' -delete
    : > "$agents_file"

    for rule_file in "$rules_dir"/*.md; do
        if [ -f "$rule_file" ]; then
            local base_name
            local output_rule
            rules_found=1
            base_name="$(basename "$rule_file" .md)"
            output_rule="${rules_dest}/${base_name}.mdc"

            {
                printf -- '---\n'
                printf 'description: Global rule imported from %s\n' "$(basename "$rule_file")"
                printf 'alwaysApply: true\n'
                printf -- '---\n\n'
                cat "$rule_file"
                printf '\n'
            } > "$output_rule"

            {
                printf '<!-- Generated by setup_cursor.sh from %s -->\n\n' "$(basename "$rule_file")"
                cat "$rule_file"
                printf '\n\n'
            } >> "$agents_file"

            print_info "Rule installed: ${base_name}.mdc"
        fi
    done

    if [ "$rules_found" -eq 0 ]; then
        print_error "No markdown rule files found in $rules_dir"
        return 1
    fi
}

setup_global_skills() {
    local repo_dir="$1"
    local target_home="$2"
    local skills_src="${repo_dir}/skills"
    local skills_dest="${target_home}/skills"
    local copied=0

    print_info "Setting up global Cursor skills"
    mkdir -p "$skills_dest"

    for skill_dir in "$skills_src"/*; do
        if [ -d "$skill_dir" ] && [ -f "$skill_dir/SKILL.md" ]; then
            rm -rf "${skills_dest}/$(basename "$skill_dir")"
            cp -R "$skill_dir" "$skills_dest/"
            print_info "Skill installed: $(basename "$skill_dir")"
            copied=1
        fi
    done

    if [ "$copied" -eq 0 ]; then
        print_warn "No skills with SKILL.md found in $skills_src"
    fi
}

main() {
    local repo_dir
    local target_home
    local rules_dir

    repo_dir="$(script_dir)"
    target_home="$(cursor_home)"
    rules_dir="${repo_dir}/rules"

    echo "========================================="
    echo "      Cursor Global Setup Script"
    echo "========================================="
    echo ""

    mkdir -p "$target_home"

    print_info "Setting up global Cursor rules"
    generate_cursor_rules "$rules_dir" "${target_home}/rules" "${target_home}/AGENTS.md"
    echo ""
    setup_global_skills "$repo_dir" "$target_home"
    echo ""

    print_info "Cursor setup complete"
    print_info "Config directory: $target_home"
}

main "$@"
