#!/bin/bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
CODEX_NPM_PACKAGE='@openai/codex'

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_command() {
    command -v "$1" >/dev/null 2>&1
}

script_dir() {
    cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
}

default_bin_dir() {
    if [ "$(id -u)" -eq 0 ] && [ -d /usr/local/bin ] && [ -w /usr/local/bin ]; then
        printf '%s\n' "/usr/local/bin"
    else
        printf '%s\n' "${HOME}/.local/bin"
    fi
}

install_bin_dir() {
    if [ -n "${CODEX_BIN_DIR:-}" ]; then
        printf '%s\n' "$CODEX_BIN_DIR"
    else
        default_bin_dir
    fi
}

codex_home() {
    if [ -n "${CODEX_HOME:-}" ]; then
        printf '%s\n' "$CODEX_HOME"
    else
        printf '%s\n' "${HOME}/.codex"
    fi
}

append_path_to_shell_rcs() {
    local bin_dir="$1"
    local export_line="export PATH=\"${bin_dir}:\$PATH\""
    local rc_file

    case ":$PATH:" in
        *":${bin_dir}:"*) ;;
        *) export PATH="${bin_dir}:$PATH" ;;
    esac

    for rc_file in "${HOME}/.bashrc" "${HOME}/.zshrc" "${HOME}/.profile"; do
        if [ ! -f "$rc_file" ] && [ "$(basename "$rc_file")" = ".profile" ]; then
            touch "$rc_file"
        fi

        if [ -f "$rc_file" ] && ! grep -Fqs "$export_line" "$rc_file"; then
            printf '\n%s\n' "$export_line" >> "$rc_file"
        fi
    done
}

generate_combined_rules() {
    local rules_dir="$1"
    local output_file="$2"
    local rules_found=0

    mkdir -p "$(dirname "$output_file")"
    : > "$output_file"

    for rule_file in "$rules_dir"/*.md; do
        if [ -f "$rule_file" ]; then
            rules_found=1
            {
                printf '<!-- Generated by setup_codex.sh from %s -->\n\n' "$(basename "$rule_file")"
                cat "$rule_file"
                printf '\n\n'
            } >> "$output_file"
        fi
    done

    if [ "$rules_found" -eq 0 ]; then
        print_error "No markdown rule files found in $rules_dir"
        return 1
    fi
}

detect_linux_archive_name() {
    local machine
    machine="$(uname -m)"

    case "$machine" in
        x86_64|amd64)
            printf '%s\n' 'codex-x86_64-unknown-linux-musl.tar.gz'
            ;;
        aarch64|arm64)
            printf '%s\n' 'codex-aarch64-unknown-linux-musl.tar.gz'
            ;;
        *)
            print_error "Unsupported Linux architecture for binary install: $machine"
            return 1
            ;;
    esac
}

install_codex_from_release() {
    local bin_dir="$1"
    local archive_name
    local download_url
    local temp_dir

    if ! check_command curl; then
        print_error "curl is required for release-based Codex installation"
        return 1
    fi

    archive_name="$(detect_linux_archive_name)"
    download_url="https://github.com/openai/codex/releases/latest/download/${archive_name}"
    temp_dir="$(mktemp -d)"

    mkdir -p "$bin_dir"
    print_info "Installing Codex from GitHub release: ${archive_name}"

    curl -fsSL "$download_url" -o "${temp_dir}/${archive_name}"
    tar -xzf "${temp_dir}/${archive_name}" -C "$temp_dir"

    find "$temp_dir" -maxdepth 1 -type f -name 'codex-*linux-musl' -exec cp {} "${bin_dir}/codex" \;
    chmod +x "${bin_dir}/codex"
    rm -rf "$temp_dir"

    append_path_to_shell_rcs "$bin_dir"

    if check_command codex; then
        print_info "Codex installed successfully: $(codex --version)"
        return 0
    fi

    if [ -x "${bin_dir}/codex" ]; then
        print_info "Codex installed successfully at ${bin_dir}/codex"
        return 0
    fi

    print_error "Release install finished, but Codex binary was not found"
    return 1
}

install_or_upgrade_codex() {
    local bin_dir

    if [ "${SKIP_CODEX_INSTALL:-0}" = "1" ]; then
        print_warn "Skipping Codex install/upgrade because SKIP_CODEX_INSTALL=1"
        return 0
    fi

    bin_dir="$(install_bin_dir)"

    if check_command codex; then
        print_info "Codex already installed: $(codex --version)"
        if codex --help | grep -q -- '--version'; then
            print_info "Upgrading Codex with npm when available"
        fi

        if check_command npm; then
            npm install -g "$CODEX_NPM_PACKAGE"
            print_info "Codex upgrade complete: $(codex --version)"
            return 0
        fi

        print_warn "npm is unavailable, falling back to release-based Codex install"
        install_codex_from_release "$bin_dir"
        return 0
    fi

    if check_command npm; then
        print_info "Installing Codex with npm"
        npm install -g "$CODEX_NPM_PACKAGE"

        if check_command codex; then
            print_info "Codex installed successfully: $(codex --version)"
            return 0
        fi

        print_warn "npm install finished, but 'codex' is still not in PATH"
        append_path_to_shell_rcs "$bin_dir"

        if [ -x "${bin_dir}/codex" ]; then
            print_info "Codex installed successfully at ${bin_dir}/codex"
            return 0
        fi
    fi

    print_warn "npm is unavailable or did not expose codex in PATH, using release-based install"
    install_codex_from_release "$bin_dir"
}

setup_global_rules() {
    local repo_dir="$1"
    local target_home="$2"
    local rules_dir="${repo_dir}/rules"
    local target_file="${target_home}/AGENTS.md"

    print_info "Setting up global Codex rules"
    generate_combined_rules "$rules_dir" "$target_file"
    print_info "Global Codex rules written to ${target_file}"
}

setup_global_skills() {
    local repo_dir="$1"
    local target_home="$2"
    local skills_src="${repo_dir}/skills"
    local skills_dest="${target_home}/skills"
    local copied=0

    print_info "Setting up global Codex skills"
    mkdir -p "$skills_dest"

    for skill_dir in "$skills_src"/*; do
        if [ -d "$skill_dir" ] && [ -f "$skill_dir/SKILL.md" ]; then
            rm -rf "${skills_dest}/$(basename "$skill_dir")"
            cp -R "$skill_dir" "$skills_dest/"
            print_info "Skill installed: $(basename "$skill_dir")"
            copied=1
        fi
    done

    if [ "$copied" -eq 0 ]; then
        print_warn "No skills with SKILL.md found in $skills_src"
    fi
}

usage() {
    cat <<'EOF'
Usage: bash setup_codex.sh [--install-skill] [--help]

Install or update Codex. Global rules are always installed by default.

Options:
  --install-skill  Also install/update global Codex skills.
  -h, --help       Show this help message.
EOF
}

main() {
    local repo_dir
    local target_home
    local install_skill=0

    while [ "$#" -gt 0 ]; do
        case "$1" in
            --install-skill)
                install_skill=1
                ;;
            --install-rule)
                # kept for backward compatibility, now default
                shift
                continue
                ;;
            -h|--help)
                usage
                return 0
                ;;
            *)
                print_error "Unknown option: $1"
                usage
                return 1
                ;;
        esac
        shift
    done

    repo_dir="$(script_dir)"
    target_home="$(codex_home)"

    echo "========================================="
    echo "       Codex Global Setup Script"
    echo "========================================="
    echo ""

    install_or_upgrade_codex
    echo ""

    mkdir -p "$target_home"
    setup_global_rules "$repo_dir" "$target_home"
    echo ""

    if [ "$install_skill" -eq 1 ]; then
        setup_global_skills "$repo_dir" "$target_home"
        echo ""
    fi

    print_info "Codex setup complete"
    print_info "Config directory: $target_home"
}

main "$@"
