#!/bin/bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
CLAUDE_CODE_NPM_PACKAGE='@anthropic-ai/claude-code@2.1.153'

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_command() {
    command -v "$1" >/dev/null 2>&1
}

script_dir() {
    cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
}

default_bin_dir() {
    printf '%s\n' "${HOME}/.local/bin"
}

install_bin_dir() {
    if [ -n "${CC_BIN_DIR:-}" ]; then
        printf '%s\n' "$CC_BIN_DIR"
    else
        default_bin_dir
    fi
}

claude_home() {
    if [ -n "${CLAUDE_CODE_HOME:-}" ]; then
        printf '%s\n' "$CLAUDE_CODE_HOME"
    else
        printf '%s\n' "${HOME}/.claude"
    fi
}

append_path_to_shell_rcs() {
    local bin_dir="$1"
    local export_line="export PATH=\"${bin_dir}:\$PATH\""

    case ":$PATH:" in
        *":${bin_dir}:"*) ;;
        *) export PATH="${bin_dir}:$PATH" ;;
    esac

    for rc_file in "${HOME}/.bashrc" "${HOME}/.zshrc" "${HOME}/.profile"; do
        if [ ! -f "$rc_file" ] && [ "$(basename "$rc_file")" = ".profile" ]; then
            touch "$rc_file"
        fi

        if [ -f "$rc_file" ] && ! grep -Fqs "$export_line" "$rc_file"; then
            printf '\n%s\n' "$export_line" >> "$rc_file"
        fi
    done
}

generate_combined_rules() {
    local rules_dir="$1"
    local output_file="$2"
    local rules_found=0

    mkdir -p "$(dirname "$output_file")"
    : > "$output_file"

    for rule_file in "$rules_dir"/*.md; do
        if [ -f "$rule_file" ]; then
            rules_found=1
            {
                printf '<!-- Generated by setup_cc.sh from %s -->\n\n' "$(basename "$rule_file")"
                cat "$rule_file"
                printf '\n\n'
            } >> "$output_file"
        fi
    done

    if [ "$rules_found" -eq 0 ]; then
        print_error "No markdown rule files found in $rules_dir"
        return 1
    fi
}

install_claude_code_from_npm() {
    if ! check_command npm; then
        print_error "npm is required to install Claude Code"
        return 1
    fi

    print_info "Installing Claude Code via npm: ${CLAUDE_CODE_NPM_PACKAGE}"
    npm install -g "$CLAUDE_CODE_NPM_PACKAGE"

    if check_command claude; then
        print_info "Claude Code installed successfully: $(claude --version 2>/dev/null || echo 'ok')"
        return 0
    fi

    print_error "npm install finished, but 'claude' command not found in PATH"
    return 1
}

ensure_npm_user_prefix() {
    local npm_prefix
    npm_prefix="$(npm config get prefix 2>/dev/null || true)"

    # If prefix is system-level and not writable, switch to ~/.local
    if [ ! -w "${npm_prefix}/lib/node_modules" ] 2>/dev/null; then
        local user_prefix="${HOME}/.local"
        print_info "Configuring npm prefix to ${user_prefix} (avoids needing sudo)"
        npm config set prefix "$user_prefix"
        append_path_to_shell_rcs "${user_prefix}/bin"
        # Also fix ownership of any existing npm cache
        mkdir -p "${HOME}/.npm" 2>/dev/null || true
    fi
}

install_or_upgrade_claude_code() {
    local bin_dir
    local npm_prefix_before

    if [ "${SKIP_CC_INSTALL:-0}" = "1" ]; then
        print_warn "Skipping Claude Code install/upgrade because SKIP_CC_INSTALL=1"
        return 0
    fi

    npm_prefix_before="$(npm config get prefix 2>/dev/null || true)"
    ensure_npm_user_prefix
    bin_dir="$(install_bin_dir)"

    if check_command claude; then
        print_info "Claude Code already installed: $(claude --version 2>/dev/null || true)"
        # If we just switched npm prefix, always reinstall to new location
        if [ "$(npm config get prefix 2>/dev/null)" != "$npm_prefix_before" ]; then
            print_info "Reinstalling to user prefix (previously under system path)"
        else
            print_info "Attempting upgrade..."
        fi
        if check_command npm; then
            npm install -g "$CLAUDE_CODE_NPM_PACKAGE"
            print_info "Claude Code install/upgrade complete"
            return 0
        fi
        print_warn "npm is unavailable, skipping upgrade"
        return 0
    fi

    install_claude_code_from_npm
}

setup_global_rules() {
    local repo_dir="$1"
    local target_home="$2"
    local rules_dir="${repo_dir}/rules"
    local target_file="${target_home}/CLAUDE.md"

    print_info "Setting up global Claude Code rules"
    generate_combined_rules "$rules_dir" "$target_file"
    print_info "Global Claude Code rules written to ${target_file}"
}

setup_global_skills() {
    local repo_dir="$1"
    local target_home="$2"
    local skills_src="${repo_dir}/skills"
    local skills_dest="${target_home}/skills"
    local copied=0

    print_info "Setting up global Claude Code skills"
    mkdir -p "$skills_dest"

    for skill_dir in "$skills_src"/*; do
        if [ -d "$skill_dir" ] && [ -f "$skill_dir/SKILL.md" ]; then
            rm -rf "${skills_dest}/$(basename "$skill_dir")"
            cp -R "$skill_dir" "$skills_dest/"
            print_info "Skill installed: $(basename "$skill_dir")"
            copied=1
        fi
    done

    if [ "$copied" -eq 0 ]; then
        print_warn "No skills with SKILL.md found in $skills_src"
    fi
}

setup_deepseek_backend() {
    local api_key

    # Prompt for API key
    echo ""
    print_info "Please enter your DeepSeek API Key:"
    read -r api_key
    if [ -z "$api_key" ]; then
        print_error "API key cannot be empty"
        return 1
    fi

    print_info "Setting up Claude Code to use DeepSeek as backend"

    # Write settings.json with env vars (per DeepSeek official docs)
    local settings_file="${HOME}/.claude/settings.json"
    mkdir -p "$(dirname "$settings_file")"
    cat > "$settings_file" <<SETTINGS_EOF
{
  "authMethod": "api-key",
  "hasCompletedOnboarding": true,
  "theme": "dark",
  "env": {
    "ANTHROPIC_AUTH_TOKEN": "${api_key}",
    "ANTHROPIC_BASE_URL": "https://api.deepseek.com/anthropic",
    "ANTHROPIC_MODEL": "deepseek-v4-pro[1m]",
    "ANTHROPIC_DEFAULT_OPUS_MODEL": "deepseek-v4-pro[1m]",
    "ANTHROPIC_DEFAULT_SONNET_MODEL": "deepseek-v4-pro[1m]",
    "ANTHROPIC_DEFAULT_HAIKU_MODEL": "deepseek-v4-pro[1m]",
    "CLAUDE_CODE_SUBAGENT_MODEL": "deepseek-v4-pro[1m]",
    "CLAUDE_CODE_EFFORT_LEVEL": "max",
    "API_TIMEOUT_MS": "3000000",
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1"
  }
}
SETTINGS_EOF
    print_info "Claude Code settings written to ${settings_file}"

    print_info "DeepSeek backend configured successfully"
}

usage() {
    cat <<'EOF'
Usage: bash setup_cc.sh [--install-skill] [--install-rule] [--use-deepseek] [--help]

Install or update Claude Code (claude CLI from Anthropic).

Options:
  --install-skill  Also install/update global Claude Code skills.
  --use-deepseek   Configure Claude Code to use DeepSeek as the backend
                   (per https://api-docs.deepseek.com/zh-cn/quick_start/agent_integrations/claude_code).
                   Prompts for your DeepSeek API key.
  -h, --help       Show this help message.

Environment variables:
  CLAUDE_CODE_HOME   Override default Claude Code config directory (default: ~/.claude)
  CC_BIN_DIR         Override default binary install directory (default: ~/.local/bin)
  SKIP_CC_INSTALL=1  Skip Claude Code install/upgrade, only sync configs.
EOF
}

main() {
    local repo_dir
    local target_home
    local install_skill=0
    local use_deepseek=0

    while [ "$#" -gt 0 ]; do
        case "$1" in
            --install-skill)
                install_skill=1
                ;;
            --install-rule)
                # kept for backward compatibility, now default
                shift
                continue
                ;;
            --use-deepseek)
                use_deepseek=1
                ;;
            -h|--help)
                usage
                return 0
                ;;
            *)
                print_error "Unknown option: $1"
                usage
                return 1
                ;;
        esac
        shift
    done

    repo_dir="$(script_dir)"
    target_home="$(claude_home)"

    echo "========================================="
    echo "     Claude Code Global Setup Script"
    echo "========================================="
    echo ""

    install_or_upgrade_claude_code
    echo ""

    mkdir -p "$target_home"
    setup_global_rules "$repo_dir" "$target_home"
    echo ""

    if [ "$install_skill" -eq 1 ]; then
        setup_global_skills "$repo_dir" "$target_home"
        echo ""
    fi

    if [ "$use_deepseek" -eq 1 ]; then
        setup_deepseek_backend
        echo ""
    fi

    print_info "Claude Code setup complete"
    print_info "Config directory: $target_home"
}

main "$@"
